(() => {
  "use strict";

  function createTouchState() {
    return {
      active: false,
      pointerId: null,
      centerX: 0,
      centerY: 0,
      dx: 0,
      dy: 0,
    };
  }

  function createPointerState() {
    return {
      x: 0,
      y: 0,
      active: false,
    };
  }

  function createQaRuntimeState(options = null) {
    const opts = options && typeof options === "object" ? options : Object.create(null);
    return {
      runTimer: Number(opts.runInterval) || 0,
      saveRoundTripTimer: Number(opts.saveRoundTripInterval) || 0,
      runCount: 0,
      featureInventoryLogged: false,
      caveChecklistLogged: false,
      caveFieldClassificationLogged: false,
      saveSchemaLogged: false,
      passChecklistLogged: false,
      truthMapLogged: false,
      caveDisableReadinessLogged: false,
      initCallCount: 0,
      gameLoopStartCount: 0,
      caveOrbTraceKeys: new Set(),
      caveDisabledNetCounters: {
        sent: 0,
        recv: 0,
        activePayloads: 0,
        types: Object.create(null),
        recent: [],
      },
      caveV2LastRoomSummary: "",
      startMenuBindAttemptCount: 0,
      menuApiBridgeInstallCount: 0,
      frameBuckets: {
        total: 0,
        backdrop: 0,
        terrain: 0,
        world: 0,
        entities: 0,
        overlays: 0,
      },
      frameBucketSamples: 0,
    };
  }

  function createMpAutotestState() {
    return {
      active: false,
      mode: null,
      customFault: null,
      seed: "",
      rng: null,
      elapsed: 0,
      step: 0,
      actionTimer: 0,
      periodicCheckTimer: 0,
      messageQueue: [],
      messageLog: [],
      actionHistory: [],
      clients: [],
      hostConnections: new Map(),
      nextSeq: 1,
      eventStats: {
        authoritativeMutations: 0,
        clientAuthViolations: 0,
      },
      inventoryLedger: {
        totals: Object.create(null),
        dropTotals: Object.create(null),
        nonDropTotals: Object.create(null),
        fingerprint: "",
      },
      hostHash: "",
      clientHashes: new Map(),
      lastAction: "none",
      failReason: "",
      failReport: "",
      replayBundle: null,
      logLines: [],
      runningStatus: "idle",
      savedSeed: null,
      diagnostics: null,
      wallStartMs: 0,
      lastObservedStep: 0,
      lastProgressWallElapsed: 0,
      progressPercent: 0,
      expectedSteps: 0,
      maxSteps: 0,
      categoryStatus: new Map(),
      scenarioStatus: new Map(),
      currentScenarioId: null,
      featureCoverage: Object.create(null),
      actionStats: Object.create(null),
      pendingAssertions: [],
      nextHarvestProbeSeq: 1,
      harvestProbeResults: new Map(),
      harvestAssertionInconclusiveCount: 0,
      savedDebugSettings: null,
    };
  }

  function createGameState(deps = null) {
    const cfg = deps && typeof deps === "object" ? deps : Object.create(null);
    const settings = cfg.SETTINGS_DEFAULTS || Object.create(null);
    const surfaceGuardians = cfg.SURFACE_GUARDIAN_CONFIG || Object.create(null);
    const gameConfig = cfg.CONFIG || Object.create(null);
    return {
      world: null,
      surfaceWorld: null,
      player: null,
      inventory: null,
      structures: [],
      structureGrid: null,
      targetResource: null,
      targetMonster: null,
      targetAnimal: null,
      nearBench: false,
      nearBenchStructure: null,
      nearStation: null,
      nearChest: null,
      nearCave: null,
      nearCaveV2: null,
      nearHouse: null,
      nearBed: null,
      nearDock: null,
      nearInteriorMoveTarget: null,
      activeStation: null,
      activeChest: null,
      activeCave: null,
      activeCaveLayer: 0,
      activeHouse: null,
      inCave: false,
      returnPosition: null,
      caveTransition: null,
      cavePassageCooldown: 0,
      cavePassageLock: null,
      caveV2: {
        cavesById: Object.create(null),
        active: null,
        transitioning: false,
        transitionT: 0,
        transition: null,
        transitionCooldown: 0,
        transitionLock: null,
        targetOreId: null,
        targetDropId: null,
        debugLastSummary: "",
        debugLastRoomStatsKey: "",
        debugEntryAuditPending: false,
        debugLastEntryAuditKey: "",
      },
      caveDisableRecoveryPending: false,
      caveDisableRecoveryReason: "",
      caveDisableRecoveryWindow: 0,
      caveDisableRecoveryTriggered: false,
      caveDisableRecoveryRunCount: 0,
      caveDisableRecoveryLastReason: "",
      housePlayer: null,
      spawnTile: null,
      timeOfDay: 0,
      isNight: false,
      surfaceDayBurnGraceTimer: 0,
      surfaceSpawnTimer: 0,
      surfaceGuardianSpawnTimer: Number(surfaceGuardians.spawnInterval) || 0,
      gameWon: false,
      winTimer: 0,
      winSequencePlayed: false,
      winPlayerPos: null,
      promptText: "",
      promptTimer: 0,
      dirty: false,
      saveTimer: Number(gameConfig.saveInterval) || 0,
      nextDropId: 1,
      nextAnimalId: 1,
      respawnLock: false,
      checkpointTimer: 0,
      animalVocalTimer: 2.6,
      settingsTab: "settings",
      playerName: settings.playerName || "",
      musicVolume: Number(settings.musicVolume) || 0,
      sfxVolume: Number(settings.sfxVolume) || 0,
      graphicsPreset: settings.graphicsPreset || "",
      renderScale: Number(settings.renderScale) || 1,
      graphicsEffectsLevel: Number(settings.graphicsEffectsLevel) || 0,
      debugUnlocked: !!settings.debugUnlocked,
      debugMoses: false,
      debugInfiniteResources: !!settings.debugInfiniteResources,
      debugInfiniteHealth: !!settings.debugInfiniteHealth,
      debugWorldMapVisible: false,
      debugShowFps: false,
      debugPerfProfiler: false,
      debugShowAbandonedRobot: false,
      debugShowRepairableShip: false,
      debugContinentalShift: false,
      debugPlaceRepairedBoat: false,
      debugBoatPlacePending: false,
      debugLinkedCavePlacement: null,
      debugIslandDrag: null,
      autoPerfWarmupTimer: 0,
      debugSpeedMultiplier: Number(settings.debugSpeedMultiplier) || 1,
      debugWorldSpeedMultiplier: Number(settings.debugWorldSpeedMultiplier) || 1,
      debugFovMultiplier: Number(settings.debugFovMultiplier) || 1,
      houseRelocation: null,
      sleepSequence: null,
      ambientFish: [],
      ambientFishSpawnTimer: 0,
      nearShip: null,
      activeShipRepair: null,
      shipActionPending: false,
      shipControlSendTimer: 0,
      loadingVisible: false,
      loadingTitle: "",
      loadingStage: "",
    };
  }

  function createNetState(deps = null) {
    const cfg = deps && typeof deps === "object" ? deps : Object.create(null);
    const netConfig = cfg.NET_CONFIG || Object.create(null);
    const syncAudit = cfg.MP_DEBUG_SYNC_AUDIT_CONFIG || Object.create(null);
    return {
      enabled: false,
      ready: false,
      isHost: false,
      peer: null,
      hostConn: null,
      roomId: null,
      hostId: null,
      playerId: null,
      connections: new Map(),
      players: new Map(),
      pendingPlaces: new Map(),
      pendingHousePlaces: new Map(),
      pendingHouseMoves: new Map(),
      pendingBreaks: new Map(),
      debugBoatPlaceReceipts: new Map(),
      snapshotTimer: Number(netConfig.snapshotInterval) || 0,
      motionTimer: Number(netConfig.motionInterval) || 0,
      playerTimer: Number(netConfig.playerSendInterval) || 0,
      helloRetryTimer: Number(netConfig.helloRetryInterval) || 0,
      resyncTimer: 0,
      lastHostPacketAt: 0,
      snapshotSeq: 0,
      motionSeq: 0,
      localPlayerSeq: 0,
      localPlayerAckSeq: -1,
      lastSnapshotSeq: -1,
      lastMotionSeq: -1,
      remotePlayerSeq: new Map(),
      hostPlayerSeqByPeer: new Map(),
      remoteInventoryTotalsByPeer: new Map(),
      remoteInventoryFingerprintByPeer: new Map(),
      syncAuditTimer: Number(syncAudit.interval) || 0,
      syncAuditSeq: 0,
      pendingSyncAudits: new Map(),
      syncAuditLedgerTotals: null,
      syncAuditLedgerFingerprint: "",
      syncLedgerEventCounter: 0,
      syncLedgerLastEventCounter: 0,
      syncLedgerLastEventLabel: "",
      lastSentPlayerFingerprint: "",
      robotPausePingTimer: 0.2,
      localName: "",
      localColor: "",
      joinStartedAt: 0,
      joinRetryTimer: Number(netConfig.joinReconnectBase) || 0,
      joinAttempts: 0,
      joinPhase: "idle",
      snapshotAppliedAt: 0,
      joinAutoReconnectsRemaining: 1,
      joinHeartbeatTimer: Number(netConfig.joinHeartbeatInterval) || 0,
      joinFallbackSnapshotApplied: false,
      joinStaticSnapshotRequested: false,
      joinTimeoutNotified: false,
      hostConnPendingSince: 0,
      joinLastErrorCode: "",
      joinPromptGuardUntil: 0,
      connectIntent: "idle",
      hostCodeRetryCount: 0,
    };
  }

  window.ISGState = Object.freeze({
    createGameState,
    createMpAutotestState,
    createNetState,
    createPointerState,
    createQaRuntimeState,
    createTouchState,
  });
})();
